openapi: 3.0.0
info:
  version: "1.0.0"
  title: API de DoH
  description: Documentación de la API de DNS over HTTPs
servers:
  - url: http://localhost:8080/api
    description: Servidor de desarrollo

# Paths servidos por la aplicación
paths:
  /domains/{domain}:
    get:
      operationId: "api.dns.get_domain"
      tags:
        - "DNS"
      summary: "IP asociada a hostname"
      description: "Obtiene la IP asociada al domain name del host"
      parameters:
        - in: path
          name: domain
          required: true
          schema:
            type: string
          description: La ip del host a obtener
      responses:
        200:
          description: "Operación de lectura exitosa"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
        404:
          description: "No encontrado"

  /custom-domains:
    get:
      operationId: "api.dns.all_custom_domains"
      tags:
        - "DNS"
      summary: "Colección de custom domains"
      description: "Obtiene la lista de todos los dominios del sistema"
      parameters:
        - in: query
          name: q
          required: false
          schema:
            type: string
          description: valor dentro del nombre de dominio por el cual filtrar
      responses:
        200:
          description: "Operación de lectura exitosa"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Domain'
    post:
      operationId: "api.dns.new_custom_domain"
      tags:
        - "DNS"
      summary: "Alta de un nuevo custom domain"
      description: "Crea una entrada para sobreescribir la IP de un dominio en particular"
      requestBody:
        required: true
        x-body-name: 'domain'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputCustomDomain'
      responses:
        201:
          description: "Se creo el nuevo dominio correctamente"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
        400:
          description: "nombre de dominio duplicado"

  /custom-domains/{domain}:
    delete:
      operationId: "api.dns.delete_custom_domain"
      tags:
        - "DNS"
      summary: "Borrar custom domain"
      description: "Borra un dominio existente en el sistema"
      parameters:
        - in: path
          name: domain
          required: true
          schema:
            type: string
          description: El nombre del dominio a borrar
      responses:
        204:
          description: "Operación de lectura exitosa"
        404:
          description: "Dominio no encontrado"









  /alumnos:
    get:
      operationId: "api.alumnos.obtener_todos"
      tags:
        - "Alumnos"
      summary: "Colección de alumnos de la materia"
      description: "Obtiene la lista de todos los alumnos de la materia existentes en el sistema"
      responses:
        200:
          description: "Operación de lectura exitosa"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Alumno'
    post:
      operationId: "api.alumnos.crear"
      tags:
        - "Alumnos"
      summary: "Alta de un alumno de la materia"
      description: "Crea un nuevo alumno y lo agrega a la lista de alumnos de la materia"
      requestBody:
        required: true
        x-body-name: 'alumno'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InputAlumno'
      responses:
        201:
          description: "Se creo el alumno correctamente"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alumno'
        400:
          description: "DNI o padron duplicado"
  /alumnos/{id_alumno}:
    get:
      operationId: "api.alumnos.obtener_uno"
      tags:
        - "Alumnos"
      summary: "Alumno de la materia"
      description: "Obtiene un alumno particular de la materia"
      parameters:
        - in: path
          name: id_alumno
          required: true
          schema:
            type: integer
          description: El id del usuario a obtener
      responses:
        200:
          description: "Operación de lectura exitosa"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Alumno'
        404:
          description: "Alumno no encontrado"
    delete:
      operationId: "api.alumnos.borrar"
      tags:
        - "Alumnos"
      summary: "Borrar alumno de la materia"
      description: "Borra un alumno de la materia"
      parameters:
        - in: path
          name: id_alumno
          required: true
          schema:
            type: integer
          description: El id del usuario a borrar
      responses:
        204:
          description: "Operación de lectura exitosa"
        404:
          description: "Alumno no encontrado"
# Declaración de tipos de datos
components:
  schemas:
    Domain:
      type: "object"
      properties:
        domain:
          type: "string"
        ip:
          type: "string"
        custom:
          type: "boolean"
    InputCustomDomain:
      type: "object"
      properties:
        domain:
          type: "string"
        ip:
          type: "string"


    Alumno:
      type: "object"
      properties:
        id:
          type: "number"
        nombre:
          type: "string"
        dni:
          type: "string"
        padron:
          type: "string"
    InputAlumno:
      type: "object"
      properties:
        nombre:
          type: "string"
        dni:
          type: "string"
        padron:
          type: "string"
    Error:
      type: "object"
      properties:
        codigo:
          type: "number"
        mensaje:
          type: "string"
